import {Button, Heading, HStack, Stack, Text, Wrap, WrapItem} from "@chakra-ui/react";
import Navigation from "../../components/Navigation";
import Footer from "../../components/Footer";

const Page = () => {
  return (
    <Stack px={'45px'} spacing={0}>
      <Navigation/>
      <Stack textAlign={"center"} align={"center"} spacing={'30px'} py={'120px'}>
        <Heading fontSize={'50px'}>NEST Oracle<br/>The Truly Decentralized Oracle</Heading>
        <Text fontSize={'18px'} fontWeight={'bold'}>Unlike the price generated by Price Feed in the market, <br/>
          it constructs a decentralized non-cooperative gaming network and <br/>
          uses the mechanism of arbitrage and two-way options to determine <br/>
          the final price. NEST Oracle also introduces random information based <br/>
          on decentralized price flows on the chain. <br/>
        </Text>
        <HStack spacing={'48px'}>
          <Button bg={'#EAAA00'} h={'34px'} w={'160px'} borderRadius={'17px'} fontWeight={'bold'} color={'#003232'}>Developer Doc</Button>
          <Button bg={'#EAAA00'} h={'34px'} w={'160px'} borderRadius={'17px'} fontWeight={'bold'} color={'#003232'}>Github</Button>
        </HStack>
      </Stack>

      <Stack bg={"white"} align={"center"} textAlign={"center"} pt={'90px'} pb={'60px'} spacing={'44px'}>
        <Heading fontSize={'50px'}>What is NEST Oracle?</Heading>
        <Stack w={'680px'} h={'350px'} bg={'red'}>

        </Stack>
      </Stack>

      <Stack textAlign={"center"} align={"center"} spacing={'40px'} py={'138px'}>
        <Heading fontSize={'50px'}>
          Impeccable Technical<br/>Architecture
        </Heading>
        <Wrap spacing={'44px'} w={'1100px'} justify={"center"}>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
        </Wrap>
      </Stack>

      <Stack textAlign={"center"} align={"center"} py={'90px'} bg={'white'}>
        <Heading fontSize={'50px'}>
          How does NEST Oracle work?
        </Heading>
        <Stack h={'300px'}>

        </Stack>
      </Stack>

      <Stack align={"center"} pt={'44px'} pb={'138px'}>
        <Wrap justify={'center'} spacing={'44px'} w={'800px'}>
          <WrapItem>
            <Stack w={'308px'} h={'280px'} bg={'red'} borderRadius={'20px'}>
              <Text>Create Channel</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'280px'} bg={'red'} borderRadius={'20px'}>
              <Text>Create Channel</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'280px'} bg={'red'} borderRadius={'20px'}>
              <Text>Create Channel</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'280px'} bg={'red'} borderRadius={'20px'}>
              <Text>Create Channel</Text>
            </Stack>
          </WrapItem>
        </Wrap>
        <Stack pt={'68px'}>
          <Button variant={'outline'} borderRadius={'17px'} h={'34px'} border={'2px solid'} borderColor={'#EAAA00'} color={'#EAAA00'}>
            More
          </Button>
        </Stack>

        <Wrap justify={"center"} pt={'69px'} spacing={'44px'}>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
            </Stack>
          </WrapItem>
        </Wrap>
      </Stack>



      <Footer/>
    </Stack>
  )
}

export default Page