import {Button, Heading, HStack, Link, Stack, Text, useMediaQuery, Wrap, WrapItem} from "@chakra-ui/react";
import Navigation from "../../components/Navigation";
import Footer from "../../components/Footer";
import NavigationMobile from "../../components/NavigationMobile";
import FooterMobile from "../../components/FooterMobile";

const Page = () => {
  const [isDesktop] = useMediaQuery("(min-width: 768px)");

  const pcPage = (
    <Stack px={'45px'} spacing={0}>
      <Navigation/>
      <Stack textAlign={"center"} align={"center"} spacing={'30px'} py={'120px'}>
        <Heading fontSize={'50px'}>NEST Oracle<br/>The Truly Decentralized Oracle</Heading>
        <Text fontSize={'18px'} fontWeight={'bold'}>Unlike the price generated by Price Feed in the market, <br/>
          it constructs a decentralized non-cooperative gaming network and <br/>
          uses the mechanism of arbitrage and two-way options to determine <br/>
          the final price. NEST Oracle also introduces random information based <br/>
          on decentralized price flows on the chain. <br/>
        </Text>
        <HStack spacing={'48px'}>
          <Button bg={'#EAAA00'} h={'34px'} w={'160px'} borderRadius={'17px'} fontWeight={'bold'} color={'#003232'}>Developer Doc</Button>
          <Button bg={'#EAAA00'} h={'34px'} w={'160px'} borderRadius={'17px'} fontWeight={'bold'} color={'#003232'}>Github</Button>
        </HStack>
      </Stack>

      <Stack bg={"white"} align={"center"} textAlign={"center"} pt={'90px'} pb={'60px'} spacing={'44px'}>
        <Heading fontSize={'50px'}>What is NEST Oracle?</Heading>
        <Stack w={'680px'} h={'350px'} bg={'red'}>

        </Stack>
      </Stack>

      <Stack textAlign={"center"} align={"center"} spacing={'40px'} py={'138px'}>
        <Heading fontSize={'50px'}>
          Impeccable Technical<br/>Architecture
        </Heading>
        <Wrap spacing={'44px'} w={'1100px'} justify={"center"}>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
              <Text>Nodeless</Text>
            </Stack>
          </WrapItem>
        </Wrap>
      </Stack>

      <Stack textAlign={"center"} align={"center"} py={'90px'} bg={'white'}>
        <Heading fontSize={'50px'}>
          How does NEST Oracle work?
        </Heading>
        <Stack h={'300px'}>

        </Stack>
      </Stack>

      <Stack align={"center"} pt={'44px'} pb={'138px'}>
        <Wrap justify={'center'} spacing={'44px'} w={'800px'}>
          <WrapItem>
            <Stack w={'308px'} h={'280px'} bg={'red'} borderRadius={'20px'}>
              <Text>Create Channel</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'280px'} bg={'red'} borderRadius={'20px'}>
              <Text>Create Channel</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'280px'} bg={'red'} borderRadius={'20px'}>
              <Text>Create Channel</Text>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'280px'} bg={'red'} borderRadius={'20px'}>
              <Text>Create Channel</Text>
            </Stack>
          </WrapItem>
        </Wrap>
        <Stack pt={'68px'}>
          <Button variant={'outline'} borderRadius={'17px'} h={'34px'} border={'2px solid'} borderColor={'#EAAA00'} color={'#EAAA00'}>
            More
          </Button>
        </Stack>

        <Wrap justify={"center"} pt={'69px'} spacing={'44px'}>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
            </Stack>
          </WrapItem>
          <WrapItem>
            <Stack w={'308px'} h={'352px'} bg={'red'} borderRadius={'20px'}>
            </Stack>
          </WrapItem>
        </Wrap>
      </Stack>



      <Footer/>
    </Stack>
  )

  const mobilePage = (
    <Stack>
      <NavigationMobile/>
      <Stack textAlign={"center"} align={"center"} py={'90px'}>
        <Heading fontSize={'25px'} fontWeight={'bold'}>NEST Oracle,<br/>
          The Truly<br/>
          Decentralized Oracle
        </Heading>
        <Text fontSize={'12.5px'} fontWeight={'600'}>Unlike the price generated by Price<br/>
          Feed in the market, it constructs a<br/>
          decentralized non-cooperative gaming<br/>
          network and uses the mechanism<br/>
          of arbitrage and two-way options to<br/>
          determine the final price. NEST<br/>
          Oracle also introduces random<br/>
          information based on decentralized<br/>
          price flows on the chain.<br/>
        </Text>
        <Stack spacing={'30px'} pt={'20px'}>
          <Button w={'170px'} minH={'44px'}>
            Developer Doc
          </Button>
          <Button w={'170px'} minH={'44px'}>
            Github
          </Button>
        </Stack>
      </Stack>
      <Stack textAlign={"center"} align={"center"} py={'120px'} bg={'rgba(255, 255,255, 0.7)'} spacing={'80px'} px={'24px'}>
        <Heading fontSize={'25px'}>What is <br/>
        NEST Oracle?</Heading>
        <Stack w={'full'} h={'190px'} bg={'red'}>

        </Stack>
      </Stack>
      <Stack align={"center"} textAlign={"center"} px={'24px'} pb={'62px'}>
        <Heading fontSize={'25px'}>
          Impeccable Technical<br/>
          Architecture
        </Heading>
        <Wrap w={'full'} spacing={'20px'} justify={'center'}>
          <WrapItem h={'190px'} w={'44%'} bg={"red"} borderRadius={'17px'}>
            <Stack >
              <Text>Hello</Text>
            </Stack>
          </WrapItem>
          <WrapItem h={'190px'} w={'44%'} bg={"red"} borderRadius={'17px'}>
            <Stack >
              <Text>Hello</Text>
            </Stack>
          </WrapItem>
          <WrapItem h={'190px'} w={'44%'} bg={"red"} borderRadius={'17px'}>
            <Stack >
              <Text>Hello</Text>
            </Stack>
          </WrapItem>
          <WrapItem h={'190px'} w={'44%'} bg={"red"} borderRadius={'17px'}>
            <Stack >
              <Text>Hello</Text>
            </Stack>
          </WrapItem>
        </Wrap>
      </Stack>
      <Stack align={"center"} textAlign={"center"} spacing={'44px'}>
        <Heading>
          How does NEST<br/> Oracle work?
        </Heading>
        <Stack w={'full'} h={'400px'}>

        </Stack>
      </Stack>
      <Stack py={'62px'} px={'24px'} spacing={'24px'}>
        <Stack px={'38px'} py={'100px'} borderRadius={'17px'} boxShadow={'0px 0px 45px 5px #E5E5E5'}>
          <Text fontSize={'17px'} fontWeight={'bold'}>Create Channel</Text>
          <Text fontSize={'12.5px'} fontWeight={'600'}>Anyone can create a channel. Open
            a decentralized oracle with one click.
          </Text>
          <Stack h={'30px'}>
          </Stack>
          <Link href={''} color={'#00A0E9'} fontSize={'12.5px'} fontWeight={600}>Create your channel</Link>
        </Stack>

        <Stack px={'38px'} py={'100px'} borderRadius={'17px'} boxShadow={'0px 0px 45px 5px #E5E5E5'}>
          <Text fontSize={'17px'} fontWeight={'bold'}>Create Channel</Text>
          <Text fontSize={'12.5px'} fontWeight={'600'}>Anyone can create a channel. Open
            a decentralized oracle with one click.
          </Text>
          <Stack h={'30px'}>
          </Stack>
          <Link href={''} color={'#00A0E9'} fontSize={'12.5px'} fontWeight={600}>Create your channel</Link>
        </Stack>

        <Stack px={'38px'} py={'100px'} borderRadius={'17px'} boxShadow={'0px 0px 45px 5px #E5E5E5'}>
          <Text fontSize={'17px'} fontWeight={'bold'}>Create Channel</Text>
          <Text fontSize={'12.5px'} fontWeight={'600'}>Anyone can create a channel. Open
            a decentralized oracle with one click.
          </Text>
          <Stack h={'30px'}>
          </Stack>
          <Link href={''} color={'#00A0E9'} fontSize={'12.5px'} fontWeight={600}>Create your channel</Link>
        </Stack>

        <Stack align={"center"} pt={'44px'}>
          <Button w={'190px'} variant={"outline"} minH={'44px'}>
            More
          </Button>
        </Stack>
      </Stack>
      <Stack px={'24px'} spacing={'24px'} pb={'64px'}>
        <Stack w={'full'} h={'300px'} bg={'red'} borderRadius={'14px'}>

        </Stack>
        <Stack w={'full'} h={'300px'} bg={'red'} borderRadius={'14px'}>

        </Stack>
        <Stack w={'full'} h={'300px'} bg={'red'} borderRadius={'14px'}>

        </Stack>
      </Stack>
      <FooterMobile/>
    </Stack>
  )

  if (!isDesktop) {
    return mobilePage
  } else {
    return (
      pcPage
    )
  }
}

export default Page