import {
  Stack,
  Text,
  Heading,
  HStack,
  Button,
  chakra,
  Box,
  Link, Divider, useMediaQuery
} from "@chakra-ui/react";
import Navigation from "../components/Navigation";
import Footer from "../components/Footer";
import {useEffect, useState} from "react";
import gtag, {install} from 'ga-gtag'
import Head from "next/head";
import NavigationMobile from "../components/NavigationMobile";
import FooterMobile from "../components/FooterMobile";
import {useRouter} from "next/router";

export default function Home() {
  const [start, setStart] = useState(0)
  const [isMobile] = useMediaQuery("(max-width: 768px)");
  const router = useRouter();

  const developmentPath = [
    {title: `2018.12 v1.0`, desc: `Start! A lending\nprotocol goes live.`},
    {title: '2019.12 v2.0', desc: `NEST oracle V1.0\ngoes live.`},
    {
      title: '2020.07 v3.0',
      desc: `NEST oracle upgraded.\nOpen all oracle tracks\nand supported all\nERC20 Token/ETH price`
    },
    {title: '2021.04 v3.6', desc: `Voting governance\nmodule was added`},
    {title: '2021.11 v4.1', desc: `NEST oracle upgraded.\nAllows anyone\nto build their oracle\nfor their project.`},
    {title: '2021.12 v4.3', desc: `NEST oracle upgraded.\nAllows each channel for\nmultiple quotation pairs.`},
    {title: '2022.07 v5.0', desc: `Merge FORT protocol\nNEST protocol= NEST oracle\n+ NESTFi +PVM`},
    {title: '2023.02.10', desc: `NEST protocol upgraded.\nNEST launched the decentralized martingale network`}
  ]

  const products = [
    {
      image: ``,
      title: `NEST Token`,
      desc: `$NEST token is the native token of the whole NEST Protocol ecosystem and has been listed on more than 15 exchanges, including Huobi, Coinbase etc. $NEST can be burned or generated according to the on-chain instructions. `,
      button: `Get $NEST`,
      link: ``,
    },
    {
      image: ``,
      title: `NEST FI`,
      desc: `NEST Fi is a decentralized perpetual exchange. Trading requires neither market makers nor LPs, and smart contracts are the biggest seller in the system. Any transaction based on martingale information flow that traders require can be fulfilled.`,
      button: `Start Trading`,
      link: ``,
    },
    {
      image: ``,
      title: `Cyber Ink`,
      desc: `NEST Cyber Ink is a collection of 10,000 NFTs on the blockchain. Each Cyber Ink can unlock the NEST Fi membership and additional benefits. Members can get Cyber Ink on the official web, Element, OpenSea and other secondary NFT markets.`,
      button: `More on NTFs`,
      link: ``,
    },
    {
      image: ``,
      title: `NEST Oracle`,
      desc: `NEST oracle is the only genuinely decentralized oracle in the market currently. Unlike the market's final price generated by the Price Feed, it builds a decentralized non-cooperative game network to determine the final price through arbitrage and two-way options. It introduces the random information of decentralized price flow into the chain.`,
      button: `More Details`,
      link: ``,
    },
    {
      image: ``,
      title: `NEST Craft`,
      desc: `NEST Craft is a combination of martingale functions, similar to the Ethereum virtual machine. It will significantly broaden the scope of NEST's application, transforming it into a chain infrastructure that will enable anyone to create more NEST-based applications.`,
      button: `Start Building`,
      link: ``,
    },
  ]
  const superiority = [
    {
      title: 'More Advanced Derivatives Trading Structures',
      desc: `Based on the benefit of Martingale Network, the system uses smart contracts to eliminate market markers and LPs while providing traders with nearly infinite liquidity through risk sharing.`,
      icon: ``
    },
    {
      title: 'More Stable Price Oracles',
      desc: `NEST Oracle provides a secure and stable decentralized price stream. It takes 51% of the assets in the Oracle network to form a price attack. And it is entirely open and free of charge, allowing price offers and verifiers to verify prices.`,
      icon: ``
    },
    {
      title: 'Deflationary Economic Model',
      desc: `All users trade with $NEST smart contracts, burning $NEST to obtain the corresponding financial assets, such as futures, options, synthetic assets, etc. So the $NEST burned will exceed the $NEST generated, which allows the economic model to deflate and the $NEST price to rise.`,
      icon: ``
    },
  ]

  const title = "NEST Protocol | The most important infrastructure after ETH"
  const description = "NEST Protocol is the stochastic computer based on PVM, enables the generation and programming of stochastic assets."

  const SEO = (
    <Head>
      <title>{title}</title>
      <meta name="og:title" content={title}/>
      <meta name="twitter:title" content={title}/>
      <meta name="description" content={description}/>
      <meta name="og:description" content={description}/>
      <meta name="twitter:description" content={description}/>
    </Head>
  )

  useEffect(() => {
    install('G-ELV55124T4');
  }, [])

  const pcPage = (
    <Stack bgSize={'cover'} bgImage={"image/Home/Home_bg.jpg"} bgPosition={"center"}>
      {SEO}
      <Navigation/>
      <Stack w={'100%'} h={'100%'} spacing={0} pb={'120px'}>
        <Stack h={'480px'} bg={'red'}>

        </Stack>
        <Stack pt={'40px'} pb={'120px'}>
          <Stack spacing={'16px'}>
            <Heading fontSize={'48px'} lineHeight={'60px'} textAlign={"center"}>NEST PROTOCOL<br/>A Decentralized
              Martingale Network</Heading>
            <Text textAlign={"center"} fontWeight={'600'} fontSize={'21px'}>Trading with smart contract. No market
              makers. No LPs</Text>
            <HStack pt={'8px'} justify={"center"}>
              <Button minH={'44px'} fontSize={'25px'} onClick={() => {
                gtag('event', 'clickApp2', {
                  'from': 'desktop page'
                })
                window.open('https://finance.nestprotocol.org/', '_blank')
              }}>
                Explore NEST
              </Button>
            </HStack>
          </Stack>
        </Stack>
        <Stack pb={'120px'} spacing={'40px'}>
          <Text fontSize={'32px'} lineHeight={'44px'} fontWeight={'700'} textAlign={"center"}>The superiority of NEST
            Protocol</Text>
          <Stack direction={'row'} justifyContent={'center'} spacing={'24px'}>
            {
              superiority.map((item, index) => (
                <Stack minW={'520px'} width={'520px'} bg={'white'} borderRadius={'12px'} minH={'374px'} key={index}>
                  <Stack minH={'160px'}>
                  </Stack>
                  <Stack px={'24px'} spacing={'12px'}>
                    <Text textAlign={"center"} fontWeight={'700'} fontSize={'20px'}
                          lineHeight={'28px'}>{item.title}</Text>
                    <Text fontWeight={'700'} fontSize={'16px'} lineHeight={'22px'}
                          color={'rgba(3, 3, 8, 0.6)'}>{item.desc}</Text>
                  </Stack>
                </Stack>
              ))
            }
          </Stack>
        </Stack>
        <Stack py={'40px'} px={'150px'}>
          <Text fontSize={'32px'} lineHeight={'44px'} fontWeight={'700'}>Get started</Text>
          <Text fontSize={'16px'} lineHeight={'22px'} fontWeight={'700'} color={'rgba(3, 3, 8, 0.6)'}>As the
            infrastructure of the decentralized field, a new trading paradigm, martingale trading, proposed by the NEST
            Protocol, makes good use of the technical characteristics of the blockchain and provides traders with
            unlimited liquidity through risk sharing. It can be used, including decentralized contract exchanges,
            financial derivatives supermarkets, on-chain and off-chain risk hedging etc.</Text>
        </Stack>
        <Stack px={'150px'} pt={'40px'} spacing={'40px'}>
          {
            products.map((item, index) => (
              <Stack direction={'row'} p={'40px'} bg={'white'} justify={'space-between'}
                     flexDirection={index % 2 ? "row" : "row-reverse"} borderRadius={'12px'} key={index}>
                <Stack height={'320px'} width={'40%'} bg={'blue'}></Stack>
                <Stack spacing={'16px'} width={'40%'} justify={"center"}>
                  <Text fontSize={'32px'} lineHeight={'44px'} fontWeight={'700'}>{item.title}</Text>
                  <Text fontSize={'16px'} lineHeight={'22px'} fontWeight={'700'}
                        color={'rgba(3, 3, 8, 0.6)'}>{item.desc}</Text>
                  <HStack pt={'8px'}>
                    <Button onClick={() => {
                      router.push(item.link)
                    }}>{item.button}</Button>
                  </HStack>
                </Stack>
              </Stack>
            ))
          }
        </Stack>
        <Stack py={'120px'}>
          <Heading fontSize={'50px'} textAlign={"center"}>Development path</Heading>
          <Text pt={'12px'} fontSize={'21px'} fontWeight={'bold'} textAlign={"center"}>The NEST community always insists<br/>on
            decentralization and innovation</Text>
          <HStack px={'45px'} pt={'80px'} align={"start"}>
            <chakra.img src={'/svg/right_icon.svg'} w={'44px'} h={'44px'} transform={'rotate(180deg)'}
                        opacity={start === 0 ? 0.5 : 1}
                        cursor={"pointer"}
                        onClick={() => {
                          if (start > 0) {
                            setStart(start - 4)
                          }
                        }}/>
            <Stack w={'full'} spacing={'-36px'} align={"center"}>
              <Stack h={'44px'} w={'full'} justify={"center"} px={'15px'}>
                <Divider h={'1px'} color={'#C9C9C9'}/>
              </Stack>
              <HStack px={'45px'} justify={"space-around"} w={'full'} align={"start"}>
                {developmentPath.slice(start, start + 5).map((item, index) => (
                  <Stack key={index} align={"center"} w={'200px'} h={'180px'}>
                    <chakra.img src={'/image/Home/01-icon-03.png'} h={'24px'} w={'36px'} alt={''} mb={'22px'}/>
                    <Text fontSize={'17px'} fontWeight={'bold'}>{item.title}</Text>
                    <Text fontSize={'15px'} fontWeight={'600'} textAlign={"center"}>{item.desc}</Text>
                  </Stack>
                ))}
              </HStack>
            </Stack>
            <chakra.img src={'/svg/right_icon.svg'} w={'44px'} h={'44px'} cursor={"pointer"}
                        opacity={start + 4 > developmentPath.length ? 0.5 : 1}
                        onClick={() => {
                          if (start < developmentPath.length - 4) {
                            setStart(start + 4)
                          }
                        }}/>
          </HStack>
        </Stack>
        <Stack direction={"row"} py={'40px'} justify={'space-between'} px={'200px'}>
          <Text fontSize={'28px'} lineHeight={'40px'} fontWeight={'700'}>Over <span
            style={{color: 'rgba(234, 170, 0, 1)'}}>1 MILLION</span> community members, Join us</Text>
          <Stack direction={'row'} spacing={'45px'}>
            <Stack>
              <svg width="36" height="30" viewBox="0 0 36 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M35.3333 4.18805C34.0462 4.75613 32.6636 5.13997 31.21 5.31346C32.6929 4.4291 33.8304 3.02579 34.3669 1.35533C32.9796 2.17521 31.4427 2.77092 29.8073 3.09028C28.497 1.70232 26.6319 0.833313 24.5664 0.833313C20.6018 0.833313 17.3863 4.03605 17.3863 7.98804C17.3863 8.54691 17.4511 9.09042 17.5713 9.61551C11.6013 9.31612 6.3126 6.46805 2.77036 2.14143C2.15379 3.20082 1.79926 4.4291 1.79926 5.73722C1.79926 8.21834 3.06786 10.4093 4.99313 11.6913C3.81546 11.6529 2.70871 11.332 1.74068 10.7962V10.8883C1.74068 14.3536 4.2147 17.2447 7.50105 17.9018C6.89681 18.0645 6.26327 18.1505 5.6097 18.1505C5.14727 18.1505 4.69563 18.1075 4.25786 18.0246C5.17193 20.865 7.82321 22.9347 10.9662 22.9899C8.50762 24.9091 5.41086 26.053 2.04743 26.053C1.46785 26.053 0.89597 26.0192 0.333344 25.9532C3.5118 27.9844 7.28525 29.1666 11.3392 29.1666C24.5494 29.1666 31.7711 18.2687 31.7711 8.81713C31.7711 8.51006 31.7634 8.19992 31.7495 7.89285C33.1522 6.88259 34.3699 5.62514 35.3303 4.19266L35.3333 4.18805Z"
                  fill="#030308" fill-opacity="0.6"/>
              </svg>
            </Stack>
            <Stack>
              <svg width="34" height="34" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd"
                      d="M17 33.6666C26.2048 33.6666 33.6667 26.2047 33.6667 17C33.6667 7.79523 26.2048 0.333313 17 0.333313C7.79526 0.333313 0.333344 7.79523 0.333344 17C0.333344 26.2047 7.79526 33.6666 17 33.6666ZM26.1576 10.6188C26.3117 8.9544 24.4616 9.63976 24.4616 9.63976C23.0955 10.177 21.6867 10.7229 20.2626 11.2747C15.847 12.9858 11.2852 14.7536 7.39913 16.4933C5.29201 17.2277 6.52545 17.962 6.52545 17.962L9.86601 18.9411C11.4078 19.3816 12.2301 18.8921 12.2301 18.8921L19.4251 14.2415C21.9947 12.577 21.378 13.9477 20.7613 14.5352L15.365 19.4306C14.5427 20.116 14.9539 20.7034 15.3136 20.9971C16.3332 21.8518 18.8413 23.4154 19.9363 24.098C20.2212 24.2756 20.4105 24.3936 20.4529 24.4239C20.7099 24.6198 22.0975 25.5009 23.0226 25.3051C23.9477 25.1093 24.0505 23.9834 24.0505 23.9834L25.2839 16.2975C25.4689 14.9632 25.6811 13.6807 25.8506 12.6564C26.0106 11.6889 26.1326 10.9518 26.1576 10.6188Z"
                      fill="#030308" fill-opacity="0.6"/>
              </svg>
            </Stack>
            <Stack>
              <svg width="34" height="33" viewBox="0 0 34 33" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd"
                      d="M17 0.333313C7.79165 0.333313 0.333313 7.79165 0.333313 17C0.333313 24.375 5.10415 30.6041 11.7291 32.8125C12.5625 32.9583 12.875 32.4583 12.875 32.0208C12.875 31.625 12.8541 30.3125 12.8541 28.9166C8.66665 29.6875 7.58331 27.8958 7.24998 26.9583C7.06248 26.4791 6.24998 25 5.54165 24.6041C4.95831 24.2916 4.12498 23.5208 5.52081 23.5C6.83331 23.4791 7.77081 24.7083 8.08331 25.2083C9.58331 27.7291 11.9791 27.0208 12.9375 26.5833C13.0833 25.5 13.5208 24.7708 14 24.3541C10.2916 23.9375 6.41665 22.5 6.41665 16.125C6.41665 14.3125 7.06248 12.8125 8.12498 11.6458C7.95831 11.2291 7.37498 9.52081 8.29165 7.22915C8.29165 7.22915 9.68748 6.79165 12.875 8.93748C14.2083 8.56248 15.625 8.37498 17.0416 8.37498C18.4583 8.37498 19.875 8.56248 21.2083 8.93748C24.3958 6.77081 25.7916 7.22915 25.7916 7.22915C26.7083 9.52081 26.125 11.2291 25.9583 11.6458C27.0208 12.8125 27.6666 14.2916 27.6666 16.125C27.6666 22.5208 23.7708 23.9375 20.0625 24.3541C20.6666 24.875 21.1875 25.875 21.1875 27.4375C21.1875 29.6666 21.1666 31.4583 21.1666 32.0208C21.1666 32.4583 21.4791 32.9791 22.3125 32.8125C25.6211 31.6955 28.4962 29.5691 30.533 26.7325C32.5698 23.896 33.6658 20.4921 33.6666 17C33.6666 7.79165 26.2083 0.333313 17 0.333313Z"
                      fill="#030308" fill-opacity="0.6"/>
              </svg>
            </Stack>
            <Stack>
              <svg width="29" height="32" viewBox="0 0 29 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M11.7983 11.9499C6.89117 11.7132 3.48017 13.4628 1.56532 17.1987C-1.30692 22.8025 1.06689 31.9722 10.649 31.9722C20.2312 31.9722 20.5083 22.7128 20.5083 21.7428C20.5083 21.0962 20.5083 17.4803 20.5083 10.8955C22.5578 12.1936 24.2858 12.975 25.6923 13.2398C27.0988 13.5044 27.9929 13.6218 28.3748 13.5917V8.19525C27.0738 8.03842 25.9488 7.73942 24.9997 7.29842C23.5761 6.63692 20.7531 4.80092 20.7531 2.11007C20.755 2.12323 20.755 1.42911 20.7531 0.02771H14.8214C14.8038 13.2078 14.8038 20.4461 14.8214 21.7428C14.8479 23.6879 13.339 26.4088 10.2796 26.4088C7.22017 26.4088 5.71125 23.6901 5.71125 21.9366C5.71125 20.8631 6.08 19.3071 7.60425 18.1548C8.50817 17.4715 9.76275 17.1987 11.7983 17.1987C11.7983 16.569 11.7983 14.8194 11.7983 11.9499Z"
                  fill="#030308" fill-opacity="0.6"/>
              </svg>
            </Stack>
          </Stack>
        </Stack>
        <Stack py={'120px'} align={"center"} spacing={'48px'}>
          <Heading fontSize={'50px'} textAlign={"center"}>Blogs</Heading>
          <HStack spacing={'44px'}>
            <Stack w={'308px'} bg={"white"} borderRadius={'20px'} spacing={0} cursor={"pointer"} onClick={() => {
              window.open('/blogs/Coinbase-Announces-Planned-Listing-of-Tokens-Adds-NEST', '_blank')
            }}>
              <chakra.img src={'/image/Home/01-card-01@2x.png'} alt={''}/>
              <Stack spacing={'10px'} p={'20px'} h={'230px'}>
                <Text fontSize={'18px'} fontWeight={'bold'}>Coinbase Announces Planned Listing of Tokens, Adds $NEST
                  to ‘Experimental Asset’ Label</Text>
                <Text fontSize={'13px'} fontWeight={'600'} color={'#878787'}>Leading United States-based
                  cryptocurrency</Text>
                <Text fontSize={'13px'} fontWeight={500} color={'#878787'}>July 25, 2022</Text>
              </Stack>
            </Stack>
            <Stack w={'308px'} bg={"white"} borderRadius={'20px'} spacing={0} cursor={'pointer'} onClick={() => {
              window.open('/blogs/NEST-Protocol-A-New-Paradigm-of-Game-Theoretic-Oracle', '_blank')
            }}>
              <chakra.img src={'/image/Home/01-card-02@2x.png'} alt={''}/>
              <Stack spacing={'20px'} p={'20px'} h={'230px'}>
                <Text fontSize={'18px'} fontWeight={'bold'}>NEST Protocol: A New Paradigm of Game Theoretic
                  Oracle</Text>
                <Text fontSize={'13px'} fontWeight={'600'} color={'#878787'}>Blockchain innovation defined the major
                  part of the last decade, with</Text>
                <Text fontSize={'13px'} fontWeight={500} color={'#878787'}>Jun 9, 2022</Text>
              </Stack>
            </Stack>
            <Stack w={'308px'} bg={"white"} borderRadius={'20px'} spacing={0} cursor={"pointer"} onClick={() => {
              window.open('/blogs/NEST-RSS-FEED-INTEGRATED-WITH-CRYPTO.COM-PRICE-PAGE', '_blank')
            }}>
              <chakra.img src={'/image/Home/01-card-03@2x.png'} alt={''}/>
              <Stack spacing={'20px'} p={'20px'} h={'230px'}>
                <Text fontSize={'18px'} fontWeight={'bold'}>NEST’s RSS FEED INTEGRATED WITH CRYPTO.COM PRICE
                  PAGE</Text>
                <Text fontSize={'13px'} fontWeight={'600'} color={'#878787'}>Through Crypto.com’s NEST Price Page,
                  you
                  can now directly access NEST’s</Text>
                <Text fontSize={'13px'} fontWeight={500} color={'#878787'}>May 6, 2022</Text>
              </Stack>
            </Stack>
          </HStack>
          <Box pt={'20px'}>
            <Button variant={'outline'} onClick={() => {
              window.open('/blogs/')
            }}>
              More
            </Button>
          </Box>
        </Stack>
        <Stack spacing={'80px'}>
          <Heading fontSize={'50px'} textAlign={"center"}>Integrations & Partners</Heading>
          <Stack align={"center"} spacing={'40px'} justify={"center"}>
            <HStack spacing={'40px'}>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://www.huobi.com/en-us/exchange/nest_usdt'} isExternal>
                  <chakra.img src={"/svg/huobi.svg"} h={'45px'} alt={'huobi'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://www.binance.com/'} isExternal>
                  <chakra.img src={"/svg/binance.svg"} h={'45px'} alt={'binance'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://www.coinbase.com/price/nest-protocol'} isExternal>
                  <chakra.img src={"/svg/Coinbase.svg"} h={'45px'} alt={'Coinbase'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://polygon.technology/'} isExternal>
                  <chakra.img src={"/svg/polygon.svg"} h={'45px'} alt={'polygon'}/>
                </Link>
              </Stack>
            </HStack>
            <HStack spacing={'40px'}>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://kcc.io/'} isExternal>
                  <chakra.img src={"/svg/kcc.svg"} h={'45px'} alt={'kcc'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://cointelegraph.com/'} isExternal>
                  <chakra.img src={"/svg/cointelegraph.svg"} h={'45px'} alt={'cointelegraph'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://cube.network/'} isExternal>
                  <chakra.img src={"/svg/cube.svg"} h={'45px'} alt={'cube'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://peckshield.com/'} isExternal>
                  <chakra.img src={"/svg/peckshield.svg"} h={'45px'} alt={'peckshield'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://for.tube/'} isExternal>
                  <chakra.img src={"/svg/fortube.svg"} h={'45px'} alt={'fortube'}/>
                </Link>
              </Stack>
            </HStack>
            <HStack spacing={'40px'}>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://polygon.technology/'} isExternal>
                  <chakra.img src={"/svg/polynetwork.svg"} h={'45px'} alt={'polynetwork'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://cofix.tech/'} isExternal>
                  <chakra.img src={"/svg/CoFiX.svg"} h={'45px'} alt={'CoFiX'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://www.parasset.top/'} isExternal>
                  <chakra.img src={"/svg/Parasset.svg"} h={'45px'} alt={'Parasset'}/>
                </Link>
              </Stack>
              <Stack h={'72px'} borderRadius={'full'} py={'12px'} px={'20px'} bg={'white'} justifyContent={"center"}
                     alignItems={"center"}>
                <Link href={'https://www.certik.com/'} isExternal>
                  <chakra.img src={"/svg/certik.svg"} h={'45px'} alt={'certik'}/>
                </Link>
              </Stack>
            </HStack>
            <Text fontSize={'20px'} fontWeight={'700'} lineHeight={'28px'}>Listed on more than 15 exchanges</Text>
          </Stack>
        </Stack>
      </Stack>
      <Footer/>
    </Stack>
  )

  const mobilePage = (
    <Stack h={'100%'} bgImage={'/image/Home/01-Phone-bg.jpg'} bgPosition={"center"} bgSize={'cover'}>
      {SEO}
      <NavigationMobile/>
      <Stack h={'210px'} w={'full'} bg={'red'}>

      </Stack>
      <Stack textAlign={"center"} p={'20px'} spacing={'16px'}>
        <Text fontSize={'25px'} fontWeight={'bold'}>NEST PROTOCOL<br/>A Decentralized Martingale Network</Text>
        <Text fontSize={'12.5px'} fontWeight={'600'}>Trading with smart contract. No market makers. No LPs</Text>
      </Stack>
      <HStack align={"center"} justify={"center"} p={'4px'}>
        <Button minH={'48px'}>
          Explore NEST
        </Button>
      </HStack>
      <Stack py={'80px'} spacing={'40px'}>
        <Text fontSize={'24px'} lineHeight={'32px'} fontWeight={'700'} textAlign={"center"}>The superiority of NEST
          Protocol</Text>
        <HStack spacing={'12px'} w={'full'} overflow={'scroll'} justify={'start'} px={'20px'}>
          {
            superiority.map((item, index) => (
              <Stack key={index} minW={'320px'} bg={'white'} p={'20px'}>
                <Text textAlign={'center'} fontSize={'16px'} lineHeight={'22px'} fontWeight={'700'}>{item.title}</Text>
                <Text pt={'12px'} fontSize={'14px'} lineHeight={'20px'} fontWeight={'700'}
                      color={'rgba(3, 3, 8, 0.6)'}>{item.desc}</Text>
              </Stack>
            ))
          }
        </HStack>
      </Stack>
      <Stack pt={'20px'} spacing={'12px'}>
        <Text fontSize={'24px'} fontWeight={'700'} lineHeight={'32px'} textAlign={"center"}>Get started</Text>
        <Text fontSize={'14px'} fontWeight={'700'} lineHeight={'20px'} px={'20px'} textAlign={'center'}
              color={'rgba(3, 3, 8, 0.6)'}>As the infrastructure of the decentralized field, a new trading paradigm,
          martingale trading, proposed by the NEST Protocol, makes good use of the technical characteristics of the
          blockchain and provides traders with unlimited liquidity through risk sharing. It can be used, including
          decentralized contract exchanges, financial derivatives supermarkets, on-chain and off-chain risk hedging
          etc.</Text>
      </Stack>
      <Stack px={'20px'} pt={'60px'} spacing={'20px'}>
        {
          products.map((item, index) => (
            <Stack key={index} bg={'white'} p={'20px'} align={'center'} spacing={'16px'} borderRadius={'12px'}
                   overflow={'hidden'}>
              <Text fontSize={'24px'} fontWeight={'700'} lineHeight={'32px'}>{item.title}</Text>
              <Text textAlign={'center'} fontSize={'14px'} fontWeight={'700'} lineHeight={'20px'}
                    color={'rgba(3, 3, 8, 0.6)'}>{item.desc}</Text>
              <HStack align={"center"} justify={"center"}>
                <Button>
                  {item.button}
                </Button>
              </HStack>
            </Stack>
          ))
        }
      </Stack>
      <Stack textAlign={"center"} align={"center"} pt={'80px'} pb={'40px'}>
        <Text fontSize={'24px'} lineHeight={'32px'} fontWeight={'bold'}>Development path</Text>
        <Text fontSize={'14px'} lineHeight={'20px'} fontWeight={'bold'}>The NEST community always insists<br/>on
          decentralization and
          innovation</Text>
        <HStack w={'full'} px={'20px'} py={'40px'} justify={"center"} spacing={'-16px'}>
          <chakra.div w={'1px'} h={'680px'} bg={'#C9C9C9'}/>
          <Stack spacing={'32px'}>
            {developmentPath.map((item) => (
                <HStack key={item.title} textAlign={"start"} align={'start'} spacing={'16px'}>
                  <chakra.img src={'/image/Home/01-icon-03.png'} h={'20px'} w={'30px'} alt={''}/>
                  <Stack w={'300px'}>
                    <Text fontSize={'16px'} lineHeight={'22px'} fontWeight={'bold'}> {item.title}</Text>
                    <Text fontSize={'12px'} lineHeight={'16px'} fontWeight={'400'}
                          color={'rgba(3, 3, 8, 0.6)'}>{item.desc}</Text>
                  </Stack>
                </HStack>
              )
            )}
          </Stack>
        </HStack>
      </Stack>
      <Stack bg={'white'} p={'20px'} align={"center"} spacing={'40px'}>
        <Text fontSize={'20px'} fontWeight={'700'} textAlign={"center"} lineHeight={'28px'}>Over <span
          style={{color: 'rgba(234, 170, 0, 1)'}}>1 MILLION</span> community<br/> members, Join us</Text>
        <HStack spacing={'28px'}>
          <Link>
            <svg width="36" height="30" viewBox="0 0 36 30" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path
                d="M35.3333 4.18775C34.0462 4.75583 32.6636 5.13966 31.21 5.31316C32.6928 4.4288 33.8304 3.02549 34.3669 1.35503C32.9796 2.1749 31.4427 2.77062 29.8073 3.08997C28.497 1.70202 26.6319 0.833008 24.5664 0.833008C20.6018 0.833008 17.3863 4.03575 17.3863 7.98774C17.3863 8.5466 17.4511 9.09012 17.5713 9.61521C11.6013 9.31581 6.31259 6.46774 2.77035 2.14113C2.15378 3.20052 1.79925 4.4288 1.79925 5.73691C1.79925 8.21804 3.06785 10.409 4.99312 11.691C3.81545 11.6526 2.7087 11.3317 1.74067 10.7959V10.888C1.74067 14.3533 4.21469 17.2444 7.50104 17.9015C6.8968 18.0642 6.26326 18.1502 5.60969 18.1502C5.14726 18.1502 4.69562 18.1072 4.25785 18.0243C5.17192 20.8647 7.8232 22.9344 10.9662 22.9896C8.50761 24.9088 5.41085 26.0527 2.04742 26.0527C1.46784 26.0527 0.895961 26.0189 0.333334 25.9529C3.51179 27.9841 7.28524 29.1663 11.3392 29.1663C24.5494 29.1663 31.7711 18.2684 31.7711 8.81682C31.7711 8.50975 31.7634 8.19961 31.7495 7.89254C33.1522 6.88228 34.3699 5.62483 35.3303 4.19235L35.3333 4.18775Z"
                fill="#030308" fill-opacity="0.6"/>
            </svg>
          </Link>
          <Link>
            <svg width="34" height="34" viewBox="0 0 34 34" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd"
                    d="M17 33.6663C26.2047 33.6663 33.6667 26.2044 33.6667 16.9997C33.6667 7.79493 26.2047 0.333008 17 0.333008C7.79525 0.333008 0.333332 7.79493 0.333332 16.9997C0.333332 26.2044 7.79525 33.6663 17 33.6663ZM26.1575 10.6185C26.3117 8.9541 24.4616 9.63946 24.4616 9.63946C23.0955 10.1767 21.6867 10.7226 20.2626 11.2744C15.847 12.9855 11.2852 14.7533 7.39912 16.493C5.292 17.2274 6.52544 17.9617 6.52544 17.9617L9.866 18.9408C11.4078 19.3813 12.2301 18.8918 12.2301 18.8918L19.4251 14.2412C21.9947 12.5767 21.378 13.9474 20.7613 14.5349L15.365 19.4303C14.5427 20.1156 14.9539 20.7031 15.3136 20.9968C16.3332 21.8514 18.8413 23.4151 19.9363 24.0977C20.2212 24.2753 20.4105 24.3933 20.4529 24.4236C20.7099 24.6195 22.0975 25.5006 23.0226 25.3048C23.9477 25.109 24.0504 23.983 24.0504 23.983L25.2839 16.2972C25.4689 14.9629 25.6811 13.6804 25.8505 12.6561C26.0106 11.6886 26.1326 10.9514 26.1575 10.6185Z"
                    fill="#030308" fill-opacity="0.6"/>
            </svg>
          </Link>
          <Link>
            <svg width="34" height="33" viewBox="0 0 34 33" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" clip-rule="evenodd"
                    d="M17 0.333008C7.79167 0.333008 0.333336 7.79134 0.333336 16.9997C0.333336 24.3747 5.10417 30.6038 11.7292 32.8122C12.5625 32.958 12.875 32.458 12.875 32.0205C12.875 31.6247 12.8542 30.3122 12.8542 28.9163C8.66667 29.6872 7.58334 27.8955 7.25 26.958C7.0625 26.4788 6.25 24.9997 5.54167 24.6038C4.95834 24.2913 4.125 23.5205 5.52084 23.4997C6.83334 23.4788 7.77084 24.708 8.08334 25.208C9.58334 27.7288 11.9792 27.0205 12.9375 26.583C13.0833 25.4997 13.5208 24.7705 14 24.3538C10.2917 23.9372 6.41667 22.4997 6.41667 16.1247C6.41667 14.3122 7.0625 12.8122 8.125 11.6455C7.95834 11.2288 7.375 9.52051 8.29167 7.22884C8.29167 7.22884 9.6875 6.79134 12.875 8.93717C14.2083 8.56217 15.625 8.37467 17.0417 8.37467C18.4583 8.37467 19.875 8.56217 21.2083 8.93717C24.3958 6.77051 25.7917 7.22884 25.7917 7.22884C26.7083 9.52051 26.125 11.2288 25.9583 11.6455C27.0208 12.8122 27.6667 14.2913 27.6667 16.1247C27.6667 22.5205 23.7708 23.9372 20.0625 24.3538C20.6667 24.8747 21.1875 25.8747 21.1875 27.4372C21.1875 29.6663 21.1667 31.458 21.1667 32.0205C21.1667 32.458 21.4792 32.9788 22.3125 32.8122C25.6211 31.6952 28.4962 29.5688 30.533 26.7322C32.5698 23.8957 33.6658 20.4918 33.6667 16.9997C33.6667 7.79134 26.2083 0.333008 17 0.333008Z"
                    fill="#030308" fill-opacity="0.6"/>
            </svg>
          </Link>
          <Link>
            <svg width="29" height="32" viewBox="0 0 29 32" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path
                d="M11.7983 11.9496C6.89117 11.7128 3.48017 13.4624 1.56532 17.1983C-1.30692 22.8021 1.06689 31.9718 10.649 31.9718C20.2312 31.9718 20.5083 22.7125 20.5083 21.7425C20.5083 21.0958 20.5083 17.48 20.5083 10.8951C22.5578 12.1932 24.2858 12.9746 25.6923 13.2394C27.0988 13.5041 27.9929 13.6214 28.3748 13.5913V8.19489C27.0738 8.03805 25.9488 7.73905 24.9997 7.29805C23.5761 6.63655 20.7531 4.80055 20.7531 2.1097C20.755 2.12286 20.755 1.42874 20.7531 0.0273438H14.8214C14.8038 13.2074 14.8038 20.4457 14.8214 21.7425C14.8479 23.6876 13.339 26.4084 10.2796 26.4084C7.22017 26.4084 5.71125 23.6897 5.71125 21.9362C5.71125 20.8627 6.08 19.3067 7.60425 18.1545C8.50817 17.4711 9.76275 17.1983 11.7983 17.1983C11.7983 16.5686 11.7983 14.8191 11.7983 11.9496Z"
                fill="#030308" fill-opacity="0.6"/>
            </svg>
          </Link>
        </HStack>
      </Stack>
      <Stack align={"center"} py={'62px'}>
        <Text fontSize={'25px'} fontWeight={'bold'}>Blog</Text>
        <Stack px={'24px'} w={'full'} py={'38px'}>
          <Stack bg={"white"} spacing={0} borderRadius={'20px'}>
            <chakra.img src={'/image/Home/01-card-01@2x.png'} alt={''}/>
            <Stack px={'35px'} py={'25px'} cursor={"pointer"} onClick={() => {
              window.open('/blogs/Coinbase-Announces-Planned-Listing-of-Tokens-Adds-NEST', '_blank')
            }}>
              <Text fontSize={'12.5px'} fontWeight={'bold'}>Coinbase Announces Planned Listing<br/>of Tokens, Adds
                $NEST to ‘<br/>Experimental Asset’
                Label</Text>
              <Text fontSize={'10.5px'} fontWeight={'600'} color={'#878787'}>Leading United States-based <br/>cryptocurrency
              </Text>
              <Text fontSize={'10.5px'} fontWeight={'500'} color={'#878787'}>July 25, 2022</Text>
            </Stack>
          </Stack>
        </Stack>
        <Stack>
          <Button variant={'outline'} onClick={() => {
            window.open('/blogs/')
          }}>More</Button>
        </Stack>
      </Stack>
      <Stack align={"center"} spacing={'40px'} pb={'80px'}>
        <Text fontSize={'25px'} fontWeight={'bold'} textAlign={"center"}>Integrations & Partners</Text>
        <Stack w={'full'} align={"center"} spacing={'20px'}>
          <HStack spacing={'12px'}>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://www.huobi.com/en-us/exchange/nest_usdt'} isExternal>
                <chakra.img src={"/svg/huobi.svg"} h={'25px'} alt={'huobi'}/>
              </Link>
            </Stack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://www.binance.com/'} isExternal>
                <chakra.img src={"/svg/binance.svg"} h={'25px'} alt={'binance'}/>
              </Link>
            </Stack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://www.coinbase.com/price/nest-protocol'} isExternal>
                <chakra.img src={"/svg/Coinbase.svg"} h={'25px'} alt={'Coinbase'}/>
              </Link>
            </Stack>
          </HStack>
          <HStack spacing={'12px'}>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://polygon.technology/'} isExternal>
                <chakra.img src={"/svg/polygon.svg"} h={'25px'} alt={'polygon'}/>
              </Link>
            </Stack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://kcc.io/'} isExternal>
                <chakra.img src={"/svg/kcc.svg"} h={'25px'} alt={'kcc'}/>
              </Link>
            </Stack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://cointelegraph.com/'} isExternal>
                <chakra.img src={"/svg/cointelegraph.svg"} h={'25px'} alt={'cointelegraph'}/>
              </Link>
            </Stack>
          </HStack>
          <HStack spacing={'12px'}>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://cube.network/'} isExternal>
                <chakra.img src={"/svg/cube.svg"} h={'25px'} alt={'cube'}/>
              </Link>
            </Stack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://peckshield.com/'} isExternal>
                <chakra.img src={"/svg/peckshield.svg"} h={'25px'} alt={'peckshield'}/>
              </Link>
            </Stack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://for.tube/'} isExternal>
                <chakra.img src={"/svg/fortube.svg"} h={'25px'} alt={'fortube'}/>
              </Link>
            </Stack>
          </HStack>
          <HStack spacing={'12px'}>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://polygon.technology/'} isExternal>
                <chakra.img src={"/svg/polynetwork.svg"} h={'25px'} alt={'polynetwork'}/>
              </Link>
            </Stack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://cofix.tech/'} isExternal>
                <chakra.img src={"/svg/CoFiX.svg"} h={'25px'} alt={'CoFiX'}/>
              </Link>
            </Stack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://www.parasset.top/'} isExternal>
                <chakra.img src={"/svg/Parasset.svg"} h={'25px'} alt={'Parasset'}/>
              </Link>
            </Stack>
          </HStack>
          <HStack>
            <Stack p={'8px 12px'} bg={'white'} borderRadius={'full'}>
              <Link href={'https://www.certik.com/'} isExternal>
                <chakra.img src={"/svg/certik.svg"} h={'25px'} alt={'certik'}/>
              </Link>
            </Stack>
          </HStack>
          <Text pt={'20px'} fontSize={'14px'} lineHeight={'20px'} fontWeight={'700'}>Listed on more than 15
            exchanges</Text>
        </Stack>
      </Stack>
      <FooterMobile/>
    </Stack>
  )

  if (isMobile) {
    return mobilePage
  } else {
    return (
      pcPage
    )
  }
}
